name: Executes GraalVM Native Tests
description: Executes GraalVM native tests
inputs:
  graalvm:
    description: 'GraalVM version'
    required: true
  java:
    description: 'Java version'
    required: true
runs:
  using: "composite"
  steps:
    # https://github.com/actions/virtual-environments/issues/709
    - name: "🗑 Free disk space"
      shell: bash
      run: |
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo apt-get clean
        df -h

    - name: "📥 Checkout repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "🔧 Setup GraalVM CE"
      uses: graalvm/setup-graalvm@v1
      with:
        version: ${{ inputs.graalvm }}
        java-version: ${{ inputs.java }}
        components: 'native-image'

    - name: "🔧 Setup Gradle"
      uses: gradle/gradle-build-action@v2

    - name: "❓ Optional setup step"
      shell: bash
      run: |
        [ -f ./setup.sh ] && ./setup.sh || [ ! -f ./setup.sh ]

    - name: "🛠 Build with Gradle"
      id: gradle
      shell: bash
      run: |
        if ./gradlew tasks --no-daemon --all | grep -w "nativeTest"
        then
          ./gradlew nativeTest --no-daemon --continue
        fi
      env:
        TESTCONTAINERS_RYUK_DISABLED: 'true'
        PREDICTIVE_TEST_SELECTION: "${{ github.event_name == 'pull_request' && 'true' || 'false' }}"

    - name: "📊 Publish Test Report"
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: GraalVM CI / Test Report (${{ inputs.java }})
        report_paths: '**/build/test-results/test/TEST-*.xml'
        check_retries: 'true'
