name: Stop created on-demand OCI runners
description: Finds and stops OCI runners
inputs:
  github-token:
    description: 'GitHub token to authenticate the requests'  
    required: true
  oci-compartment-ocid:
    description: The compartment OCID where to start the runners.
    required: true
  oci-runner-label-tag-value:
    description: The runner label tag value created in start-oci-runner step.
    required: true
runs:
  using: "composite"
  steps:
    - id: stop-runner
      run: |
        RUNNER_LABEL=${{ inputs.oci-runner-label-tag-value }}
        for ID in $(oci compute instance list --compartment-id ${{ inputs.oci-compartment-ocid }} | \
         jq -r ".data[] | select( .\"freeform-tags\".repository == \"$GITHUB_REPOSITORY\" and .\"freeform-tags\".label == \"$RUNNER_LABEL\" ) | .id")
        do
          oci compute instance terminate --instance-id "$ID"  --wait-for-state TERMINATED --force
        done
        RUNNERS_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runners"
        for RUNNER_ID in $(curl -X GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ inputs.github-token }}" ${RUNNERS_URL}  | \
          jq -r --arg runner_label $RUNNER_LABEL '.runners[] | select(.labels[] | .name == $runner_label) | .id');
        do
          curl -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ inputs.github-token }}" ${RUNNERS_URL}/${RUNNER_ID}
        done
      shell: bash
